version: '3.3'
services:
  app:
    build:
      context: .
    ports:
      - 28000:8000
    environment:
      - ENGINE=postgresql://sreintern:TxSyHPDoaw44396z@34.135.5.178/sreinsights_dcl
    image: sre-embarkation-manifest-backend:1.6.0
    container_name: sre-embarkation-manifest-backend
    restart: unless-stopped